### PR TITLE
Update tls.md

### PR DESCRIPTION
**Pull request by samuela**
Fix typo in `tls.md` docs.

### CODE REVIEW

**Comment by davecheney** [comment]
@samuela thank you for your change. Can you please

- Update the PR description to include the issue this PR addresses
- Please sign your commit.

**Comment by samuela** [comment]
@davecheney done

**Comment by davecheney** [comment]
@samuela can you please update the PR description to mention the issue this PR fixes. Thank you.

**Comment by davecheney** [comment]
Never mind. In future, when raising PR's please include in the PR description _what_ the PR fixes, not how it does it.

**Pull request merged**
