### PR TITLE
Hardcoded maximum TLS version 1.3

### LINKED ISSUE #672: Automatically set tls_maximum_protocol_version to opt in to TLS 1.3
Please add support for the `tls_maximum_protocol_version` envoy api parameter (like you do for `tls_minimum_protocol_version`) to allow users to opt in to TLS 1.3. See https://github.com/envoyproxy/envoy/issues/3544.

### PR DESCRIPTION
**Pull request by cromefire**
Fixes #672

### CODE REVIEW

**Comment by cromefire** [comment]
> This project uses DCO, please sign your commit with -s

Is there any way to fix that after committing?

**Comment by davecheney** [comment]
git commit -s --amend

**Comment by cromefire** [comment]
Actually it is signed:
image
image

Is it a problem that I use my Username not my `id`?

**Comment by cromefire** [comment]
Should I just redo this?

**Comment by davecheney** [comment]
If that’s easier, sure. 

https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#dco-sign-off

**Comment by cromefire** [comment]
> https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#dco-sign-off

I thing he didn't like that I used `Cromefire_` instead of `cromefire`

**Pull request closed without merging**
