### PR TITLE
cmd/contour: properly initalise glog during startup

### LINKED ISSUE #113: bug: does cmd/contour have to call flag.Parse unconditionally
```
ERROR: logging before flag.Parse: W1218 11:31:33.776933   73199 reflector.go:341] github.com/heptio/contour/internal/k8s/watcher.go:61: watch of *v1.Endpoints ended with: too old resource version: 8605078 (8606302)
```
cmd/contour uses kingpin, not flag, but I suspect the glog infection via client-go requires flag.Parse to be called unconditionally.

### PR DESCRIPTION
**Pull request by willmadison**
Fixes #113 (properly initializing glog @ startup of cmd/contour)

Signed-off-by: Will <wmadisondev@gmail.com>

### CODE REVIEW

**Comment by davecheney** [comment]
@willmadison thanks. Sorry, you'll have to fix the signed off line to make the DCO checker happy.

**Comment by willmadison** [comment]
Yea I'm trying to get the expectation down now. It must be case sensitive. Just a sec.

**Comment by davecheney** [comment]
While I have you

- a comment and a pr's description should describe what will happen when this pr is applied, not how it is implemented.

Suggestion: cmd/contour: properly initalise glog during startup

- Please reference the bug in the pr

Fixes #113

**Comment by willmadison** [comment]
@davecheney sorry about the barrage of commits. I went back and ensured that the author matched for all commits then squashed all my trial and error commits into one and pushed a clean history.

**Pull request merged**
