### PR TITLE
internal/contour: add CORS support

### LINKED ISSUE #437: Feature request: CORS support
As far as I can see, in v2 API, it can be implemented only as a http filter: https://github.com/envoyproxy/data-plane-api/blob/master/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.

In order to have secure enough defaults I think this should be disabled by default and let people enable explicitly with a new command-line parameter.

The implementation is fairly easy I can send a PR if you feel this can get into contour.

WDYT @davecheney? 

---
[@rosskukulinski copy/paste] Proposed spec:

[...]
    tls:
      # required, the name of a secret in the current namespace
      secretName: google-tls
      # other properties like cipher suites may be added later
    # if present describes the CORS policy.
    cors:
      # Specifies the origins that will be allowed to do CORS requests.
      allowOrigin:
        - www.google.com
        - google.com
      # Specifies the content for the *access-control-allow-methods*
      # header.
      allowMethods:
        - GET
        - POST
      # Specifies the content for the *access-control-allow-headers*
      # header.
      allowHeaders:
        - Content-Type
      # Specifies the content for the *access-control-expose-headers*
      # header.
      exposeHeaders:
        - Content-Type
      # Specifies the content for the *access-control-max-age* header.
      maxAge: 24h
      # Specifies whether the resource allows credentials.
      allowCredentials: true
  strategy: RoundRobin # (Optional) LB Algorithm to apply to all services, defaults for all services
[...]

### PR DESCRIPTION
**Pull request by glerchundi**
Fixes #437

Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>

### CODE REVIEW

**Comment by glerchundi** [comment]
@davecheney we're still testing as I found there is a [`CorsPolicy`](https://github.com/envoyproxy/data-plane-api/blob/8157afee63a8a0d99626c6e68ccc67166918fd5d/envoy/api/v2/route/route.proto#L609) per each `RouteAction`. I don't know how Envoy behaves/co-lives in case an empty struct is set in this parameter but a cors filter is set.

I'll tell you something during the day.

**Comment by glerchundi** [comment]
@davecheney we've empirically tested and it works.

The motivation behind this is that we have geographically separated teams working on a shared environment (API) and UI people requires the public API to accept different origins. Without CORS our development workflow is completely broken.

**Comment by davecheney** [comment]
@glerchundi I'm sorry I do not plan to merge this at this time. I'm not happy with the continued proliferation of annotations on the ingress object. The goal of contour is _not_ to expose every feature of Envoy.

I am going to close this PR as it will not be merged at this time. 

I encourage you to reach our to @rosskukulinski, @stevesloka or myself on slack or on #437 to talk about how CQRS support could be integrated into Contour using the ingressroute CRD.

**Comment by glerchundi** [comment]
Ok, it’s fair enough.

Just a nit, you wrote CQRS but wanted to say CORS, right?

How should I proceed? Modify ingress route design proposal with proper
additions for CORS and then, once accepted, start implementing it?

Thanks,

**Comment by davecheney** [comment]
re: CORS/ CQRS, yes, sorry about that mistake.

> How should I proceed? Modify ingress route design proposal with proper
additions for CORS and then, once accepted, start implementing it?

_Please_ discuss your change on this issue or on slack thoroughly before
sending any changes.

**Pull request closed without merging**
