### PR TITLE
travis.yaml: remove mod vendor step

### PR DESCRIPTION
**Pull request by davecheney**
Fixes build error on missing target

Signed-off-by: Dave Cheney <dave@cheney.net>

### CODE REVIEW

**Comment by vaamarnath** [comment]
LGTM.

**Comment by davecheney** [comment]
PTAL. Trying another way to do this.

**Comment by vaamarnath** [comment]
@davecheney I had introduced `-mod=vendor` in the Dockerfile as well. Shall I clean that up?

**Comment by davecheney** [comment]
I got you, see #955

**Pull request merged**
