### PR TITLE
CRD fqdn regex is too strict

### LINKED ISSUE #821: CRD fqdn regex is too strict
**What steps did you take and what happened:**
Attempt to create an IngressRoute with an fqdn of `my.domain.k8s`

**What did you expect to happen:**
fqdn is valid.

**Anything else you would like to add:**

**Environment:**

- Contour version: v0.8.0
- Kubernetes version: (use `kubectl version`): 1.10

### PR DESCRIPTION
**Pull request by PeteE**
Fixes #821 

Allow numbers in TLD. 

Example:   `my.domain.k8s`

### CODE REVIEW

**Comment by troy0820** [comment]
@davecheney If I make the same changes and sign the commit, will that be merged?  I want his PR to get merged but the gentle nudges don't seem to be working.

**Comment by davecheney** [comment]
@troy0820 sorry, that is not possible.

**Comment by troy0820** [comment]
No problem, I closed the PR.

**Comment by davecheney** [comment]
Thank you. I'm sorry it has to be this way, the lawyers need to see a clean
chain of custardy from any change to the person who wrote it. I know your
intentions were to be helpful but sadly the DCO process does not have a
provision for good intentions.

**Comment by davecheney** [comment]
I’ll take responsibility for merging this.

**Pull request merged**
