### PR TITLE
Removed duplicate "will"

### PR DESCRIPTION
**Pull request by lostllama**

### CODE REVIEW

**Comment by davecheney** [comment]
I'm sorry to do this, but you need to sign your commit, even for such a tiny change.

Otherwise @stevesloka can roll this into #873

**Comment by lostllama** [comment]
@davecheney Uh, I'll leave it to you guys. I made the edit via Chrome and can't really be bothered checking out the repo to remove a single word :)

**Comment by davecheney** [comment]
Thanks. I understand.

**Comment by davecheney** [comment]
I'm going to merge this without a CLA. There is no way I cannot create a competing patch which is not derived from this patch as its a one word change.

**Pull request merged**
