### PR TITLE
New templates

### PR DESCRIPTION
**Pull request by jhamilton1**
**What this PR does / why we need it**:
The PR adds standardized bug and feature-enhancement templates. Starting with sonobuoy we will apply these to all repos.

**Which issue(s) this PR fixes**
- Fixes #
N/A

**Special notes for your reviewer**:
I will start a document to track which repos have been updated with these templates.

**Release note**:
None
```
release-note
None
```
Signed-off-by: Jesse <jesse.hamilton@heptio.com>

### CODE REVIEW

**Comment by rosskukulinski** [comment]
Hi @jhamilton1 - Thanks for opening this issue.  We're currently heads down trying to get the 0.6.0-beta.1 milestone complete.  Once that's done, we'll come back and review your PR.

**Comment by jhamilton1** [comment]
Hi @rosskukulinski - Sounds good. Thanks!

**Comment by rosskukulinski** [comment]
@jhamilton1 Hi! I think we're ready to pull this back in.  Would you mind rebasing against master?

**Comment by jhamilton1** [comment]
Hi @rosskukulinski Do you still need me to rebase against the master?

**Comment by rosskukulinski** [comment]
@jhamilton1 nope! Looks like Dave merged without it. Your templates should be in place now!

**Pull request merged**
